### ISSUE TITLE
Users can activate their accounts via email

### ISSUE THREAD

**Issue by stuartc** [OpenFn/core#106]
### Registration

- User enters Sign up page
- User enters email address and password
- User is presented with a page confirming their registration, and
  requests they check their email
- User receives email with link and token

### Activation

**Happy Path**
- User clicks link, shown page confirming their activation
- Once activated a user can click a button to take them to their account page

**Sad Path**
- If the `/user/activate/:token` url is invalid (i.e. token doesn't exist)
  we show an error explaining what went wrong.
- We should provide a button that would take you to the user registration page,
  to try again.

### Todo

- [x] Show email in console when in development mode  
      For easier debugging
- [x] Show confirmation page after registration.
- [x] Generate a token on successful registration.
- [x] Attach activation link to welcome email
- [x] Add `/user/activate/:token` page to UI
- [x] On activation page visit, attempt to activate with the server.
- [x] Add `/api/user/activate/:token` endpoint to the server.
      Returning 200 or 422
- [x] Show loading spinner when activating
- [x] Show success or failure after API call
- [x] Add confirmed_at column to users table

**Comment by taylordowns2000** [comment]
User registration failure on heroku prod:
```
2016-01-22T10:05:49.719930+00:00 app[web.1]: 10:05:49.718 request_id=8bcf8f83-4006-4009-be4c-5efa73bc9080 [info] POST /api/register
2016-01-22T10:05:51.233773+00:00 heroku[router]: at=info method=POST path="/api/register" host=openfn-core.herokuapp.com request_id=8bcf8f83-4006-4009-be4c-5efa73bc9080 fwd="197.155.4.24" dyno=web.1 connect=0ms service=1546ms status=500 bytes=305
2016-01-22T10:05:51.230238+00:00 app[web.1]: 10:05:51.228 request_id=8bcf8f83-4006-4009-be4c-5efa73bc9080 [info] Sent 500 in 1509ms
2016-01-22T10:05:51.232622+00:00 app[web.1]: 10:05:51.232 [error] #PID<0.428.0> running OpenFn.Endpoint terminated
2016-01-22T10:05:51.232624+00:00 app[web.1]: Server: openfn-core.herokuapp.com:80 (http)
2016-01-22T10:05:51.232625+00:00 app[web.1]: Request: POST /api/register
2016-01-22T10:05:51.232626+00:00 app[web.1]: ** (exit) an exception was raised:
2016-01-22T10:05:51.232628+00:00 app[web.1]:     ** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
2016-01-22T10:05:51.232628+00:00 app[web.1]:         (elixir) lib/io.ex:346: IO.chardata_to_string(nil)
2016-01-22T10:05:51.232629+00:00 app[web.1]:         (elixir) lib/path.ex:467: Path.join/2
2016-01-22T10:05:51.232630+00:00 app[web.1]:         (elixir) lib/path.ex:449: Path.join/1
2016-01-22T10:05:51.232631+00:00 app[web.1]:         lib/client.ex:44: Mailgun.Client.send_without_attachments/2
2016-01-22T10:05:51.232632+00:00 app[web.1]:         (open_fn) web/controllers/registration_controller.ex:14: OpenFn.RegistrationController.create/2
2016-01-22T10:05:51.232632+00:00 app[web.1]:         (open_fn) web/controllers/registration_controller.ex:1: OpenFn.RegistrationController.action/2
2016-01-22T10:05:51.232633+00:00 app[web.1]:         (open_fn) web/controllers/registration_controller.ex:1: OpenFn.RegistrationController.phoenix_controller_pipeline/2
2016-01-22T10:05:51.232634+00:00 app[web.1]:         (open_fn) lib/phoenix/router.ex:261: OpenFn.Router.dispatch/2
```
![image](https://cloud.githubusercontent.com/assets/8732845/12507802/cf99fd4a-c100-11e5-8b21-4c9b9c4f1b41.png)

**Comment by taylordowns2000** [comment]
```
2016-01-22T11:22:27.111047+00:00 heroku[router]: at=info method=POST path="/api/register" host=openfn-core.herokuapp.com request_id=f9260a0d-e523-4799-bc37-94236a624ad5 fwd="197.155.4.24" dyno=web.1 connect=1ms service=717ms status=500 bytes=305
2016-01-22T11:22:27.105200+00:00 app[web.1]: 11:22:27.105 [error] #PID<0.378.0> running OpenFn.Endpoint terminated
2016-01-22T11:22:27.105203+00:00 app[web.1]: Server: openfn-core.herokuapp.com:80 (http)
2016-01-22T11:22:27.105204+00:00 app[web.1]: Request: POST /api/register
2016-01-22T11:22:27.105205+00:00 app[web.1]: ** (exit) an exception was raised:
2016-01-22T11:22:27.105206+00:00 app[web.1]:     ** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
2016-01-22T11:22:27.105207+00:00 app[web.1]:         (elixir) lib/io.ex:346: IO.chardata_to_string(nil)
2016-01-22T11:22:27.105208+00:00 app[web.1]:         (elixir) lib/path.ex:467: Path.join/2
2016-01-22T11:22:27.105208+00:00 app[web.1]:         (elixir) lib/path.ex:449: Path.join/1
2016-01-22T11:22:27.105209+00:00 app[web.1]:         lib/client.ex:44: Mailgun.Client.send_without_attachments/2
2016-01-22T11:22:27.105210+00:00 app[web.1]:         (open_fn) web/controllers/registration_controller.ex:24: anonymous fn/1 in OpenFn.RegistrationController.create/2
2016-01-22T11:22:27.094840+00:00 app[web.1]: 11:22:27.094 request_id=f9260a0d-e523-4799-bc37-94236a624ad5 [info] Sent 500 in 714ms
2016-01-22T11:22:27.105211+00:00 app[web.1]:         (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/3
2016-01-22T11:22:27.105214+00:00 app[web.1]:         (ecto) lib/ecto/adapters/sql.ex:582: Ecto.Adapters.SQL.transaction/8
2016-01-22T11:22:27.105215+00:00 app[web.1]:         (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
```
